server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task_management_system_db?currentSchema=task_management_system
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC+03:00

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
        descriptor:
          sql:
            BasicBinder: trace

